version: '3'

services:
  ui:
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - '${PWD}/src:/src'
      - '${PWD}/build:/build'
    ports:
      - '8080:8080'

