version: '3'

services:

  dna-ui:
    container_name: dna-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - '.:/src'
      - '/node_modules'
    ports:
      - '8080:8080'

